db2 connect to live
db2 -x "SELECT 'RUNSTATS ON TABLE '||RTRIM(TABSCHEMA)||'.'||TABNAME||' ON ALL COLUMNS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW WRITE ACCESS;' FROM SYSCAT.TABLES WHERE TYPE='T' and stats_time < '2020-04-01-13.58.19.681363' " 
db2 terminate
